version: 2

# set Python version
build:
  os: ubuntu-20.04
  tools:
    python: "miniconda3-4.7"

# build with Sphinx
sphinx:
   configuration: docs/conf.py

# the Anaconda environment
conda:
  environment: tools/environment_rietveld.yaml

