
# readthedocs YAML format version
version: 2

# set Python version
build:
  os: ubuntu-20.04
  tools:
    python: "miniconda3-4.7"
  jobs:
    pre_install:
      - bash ./docs/_static/pre_install.sh

# build with Sphinx
sphinx:
   configuration: docs/conf.py

# the Anaconda environment
conda:
  environment: tools/environment_milk.yaml

