name: spotlight-gsas2

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # Spotlight
  - klepto=0.2.2
  - matplotlib=3.5.2
  - numpy=1.23.0
  - pip=22.1.2
  - openmpi=4.1.4
  - mpi4py=3.1.3

  # GSAS-2 extras (some overlap with spotlight)
  - pyopengl
  - wxpython=4.2
  - scipy
  - pillow
  - h5py
  - imageio
  - subversion
  - requests
  - xmltodict

  - pip:
    - git+https://github.com/lanl/spotlight.git@v0.10.2
    - mystic==0.3.9
    - pyina==0.2.6
    - pathos==0.2.9
