# Example of creating an Anconda environment with Spotlight, MILK, and GSAS-II:
# conda env create -f tools/environment_rietveld.yaml

name: spotlight-rietveld

channels:
  - conda-forge
  - defaults
  - briantoby

dependencies:
  - klepto=0.2.2
  - matplotlib=3.5.2
  - numpy=1.23.0
  - pip=22.1.2
  - python=3.8
  - sphinx=5.0.2
  - sphinxcontrib-programoutput=0.16
  - gprof2dot=2019.11.30
  - openmpi=4.1.4
  - mpi4py=3.1.3

  # for volcano function example
  - scipy=1.8.1

  # for MILK
  - tqdm=4.64.0
  - prettytable=3.3.0

  # for GSAS-II
  - gsas2pkg=2
  - pyfai=0.21.3
  - pydantic=1.9.1
  - scons=4.3.0
  - spyder-kernels=2.1

  # pip packages
  - pip:
    - git+https://github.com/lanl/MILK.git@f9f7257
    - git+https://github.com/lanl/spotlight.git@c62267c
    - mystic==0.3.9
