# Example of creating an Anconda environment with Spotlight and MILK.
# This is only meant for use by readthedocs, it does not contain
# a comprehensive environment a developer or user may need:
# conda env create -f tools/environment_docs.yaml

name: spotlight-docs

channels:
  - conda-forge
  - defaults

dependencies:
  - klepto=0.2.2
  - matplotlib=3.5.2
  - numpy=1.23.0
  - pip=22.1.2
  - python=3.8
  - openmpi=4.1.4
  - mpi4py=3.1.3

  # for documentation
  - nbsphinx=0.8.9
  - sphinx=5.0.2
  - sphinxcontrib-programoutput=0.16
  - ipykernel

  # for volcano function example
  - scipy=1.8.1

  # for MILK
  - tqdm=4.64.0
  - prettytable=3.3.0

  # pip packages
  - pip:
    - git+https://github.com/lanl/MILK.git@f9f7257
    - git+https://github.com/lanl/spotlight.git@c62267c
    - mystic==0.3.9

