# Example of creating an Anconda environment with Spotlight and GSAS-II:
# conda env create -f tools/environment_gsas2.yaml
# tested with GSAS-II revision r5609

name: spotlight-gsas2

channels:
  - briantoby
  - conda-forge
  - defaults

dependencies:
  - klepto=0.2.2
  - matplotlib=3.5.2
  - numpy=1.23.0
  - pip=22.1.2
  - python=3.8
  - openmpi=4.1.4
  - mpi4py=3.1.3

  # for volcano function example
  - scipy=1.8.1

  # for ML example
  - scikit-learn=1.1.2

  # for GSAS-II
  - gsas2pkg=2

  # for GSAS-II notebook
  - jupyterlab=3.3.2

  # pip packages
  - pip:
    - git+https://github.com/lanl/spotlight.git@v0.10.2
    - mystic==0.3.9
    - pyina==0.2.6
    - pathos==0.2.9
